/**
 * Compliance services catalog — prices aligned with AddonSelector / addon_services.py
 */
export const COMPLIANCE_SERVICES_CATALOG = [
  {
    key: 'GST_REGISTRATION',
    labelKey: 'addonGstRegistration',
    defaultName: 'GST Registration',
    price: 3000,
    icon: 'Calculator',
    descriptionKey: 'complianceDescGst',
    defaultDescription: 'End-to-end GST registration support for your business.',
    searchKeywords: 'gst registration tax compliance',
    displayOrder: 1,
  },
  {
    key: 'TRADEMARK_REGISTRATION',
    labelKey: 'addonTrademarkRegistration',
    defaultName: 'Trademark Registration',
    price: 0,
    icon: 'ShieldCheck',
    descriptionKey: 'complianceDescTrademark',
    defaultDescription: 'Protect your brand with trademark registration assistance.',
    searchKeywords: 'trademark brand ip registration',
    displayOrder: 2,
  },
  {
    key: 'COMPANY_REGISTRATION',
    labelKey: 'addonCompanyRegistration',
    defaultName: 'Company / LLP / Proprietorship Registration',
    price: 0,
    icon: 'Briefcase',
    descriptionKey: 'complianceDescCompany',
    defaultDescription: 'Company, LLP, or proprietorship incorporation support.',
    searchKeywords: 'company llp proprietorship incorporation registration',
    displayOrder: 3,
  },
  {
    key: 'UDYAM_REGISTRATION',
    labelKey: 'addonUdyamRegistration',
    defaultName: 'Udyam Registration',
    price: 1500,
    icon: 'ClipboardList',
    descriptionKey: 'complianceDescUdyam',
    defaultDescription: 'MSME Udyam registration for government benefits and recognition.',
    searchKeywords: 'udyam msme registration',
    displayOrder: 4,
  },
  {
    key: 'WEBSITE_DEVELOPMENT',
    labelKey: 'addonWebsiteDevelopment',
    defaultName: 'Website Development',
    price: 0,
    icon: 'Code',
    descriptionKey: 'complianceDescWebsite',
    defaultDescription: 'Professional website development for your business presence.',
    searchKeywords: 'website development web design',
    displayOrder: 5,
  },
  {
    key: 'IEC_REGISTRATION',
    labelKey: 'addonIecRegistration',
    defaultName: 'Import Export Code (IEC) Registration',
    price: 2000,
    icon: 'Globe',
    descriptionKey: 'complianceDescIec',
    defaultDescription: 'Import Export Code registration for international trade.',
    searchKeywords: 'iec import export code trade',
    displayOrder: 6,
  },
  {
    key: 'DIGITAL_SIGNATURE',
    labelKey: 'addonDigitalSignature',
    defaultName: 'Digital Signature Certificate',
    price: 3000,
    icon: 'FileCheck',
    descriptionKey: 'complianceDescDsc',
    defaultDescription: 'Digital Signature Certificate for secure online filings.',
    searchKeywords: 'digital signature dsc certificate',
    displayOrder: 7,
  },
  {
    key: 'PROFESSIONAL_TAX',
    labelKey: 'addonProfessionalTax',
    defaultName: 'Professional Tax Registration',
    price: 2500,
    icon: 'Receipt',
    descriptionKey: 'complianceDescProfessionalTax',
    defaultDescription: 'Professional tax registration and compliance support.',
    searchKeywords: 'professional tax registration',
    displayOrder: 8,
  },
  {
    key: 'STARTUP_INDIA',
    labelKey: 'addonStartupIndia',
    defaultName: 'Startup India Registration',
    price: 3000,
    icon: 'Rocket',
    descriptionKey: 'complianceDescStartupIndia',
    defaultDescription: 'Startup India recognition and registration assistance.',
    searchKeywords: 'startup india registration dpiit',
    displayOrder: 9,
  },
];

/** Shape used by AddonSelector checkout */
export const ADDON_SERVICES_FROM_CATALOG = COMPLIANCE_SERVICES_CATALOG.map((item) => ({
  key: item.key,
  labelKey: item.labelKey,
  price: item.price,
  contactOnly: item.price === 0,
}));
