const CREATOR_FIELDS_BY_ROLE = {
  STUDENT: [
    'about',
    'headline',
    'role',
    'industry',
    'education',
    'graduationYear',
    'githubProfile',
    'skills',
    'location',
    'expectedPriceAmount',
    'expectedPricePeriod',
    'linkedInProfileUrl',
    'whyImHere',
    'introductionVideoLink',
    'resumeDriveLink',
    'preferredWorkType',
    'availability',
    'languagesKnown',
  ],
  FREELANCER: [
    'about',
    'headline',
    'role',
    'industry',
    'experience',
    'socialMediaProfile',
    'skills',
    'location',
    'expectedPriceAmount',
    'expectedPricePeriod',
    'linkedInProfileUrl',
    'whyImHere',
    'introductionVideoLink',
    'portfolioWebsiteLink',
    'preferredWorkType',
    'availability',
    'industryExpertise',
    'languagesKnown',
  ],
  JOB_SEEKER: [
    'about',
    'headline',
    'role',
    'industry',
    'education',
    'experience',
    'githubProfile',
    'skills',
    'location',
    'expectedPriceAmount',
    'expectedPricePeriod',
    'linkedInProfileUrl',
    'whyImHere',
    'introductionVideoLink',
    'resumeDriveLink',
    'preferredWorkType',
    'languagesKnown',
  ],
  EMPLOYEE: [
    'about',
    'headline',
    'role',
    'industry',
    'currentCompany',
    'designation',
    'experience',
    'skills',
    'location',
    'expectedPriceAmount',
    'expectedPricePeriod',
    'linkedInProfileUrl',
    'whyImHere',
    'introductionVideoLink',
    'portfolioWebsiteLink',
    'preferredWorkType',
    'industryExpertise',
    'availability',
    'languagesKnown',
  ],
 EMPLOYER: [
    'about',
    'headline',
    'role',
    'industry',
    'companyName',
    'designation',
    'roleDescription',
    'hiringFor',
    'skills',
    'location',
    'whyImHere',
    'portfolioWebsiteLink',
    'preferredWorkType',
    'industryExpertise',
    'companyWebsite',
    'languagesKnown',
  ],
  MENTOR: [
    'about',
    'headline',
    'role',
    'industry',
    'experience',
    'mentorshipTopics',
    'skills',
    'location',
    'linkedInProfileUrl',
    'whyImHere',
    'portfolioWebsiteLink',
    'industryExpertise',
    'availability',
    'languagesKnown',
  ],
  INVESTOR: [
    'about',
    'headline',
    'role',
    'industry',
    'investmentFocus',
    'investmentStage',
    'ticketSize',
    'skills',
    'location',
    'whyImHere',
    'industryExpertise',
    'languagesKnown',
  ],
  FOUNDER_CO_FOUNDER: [
    'about',
    'headline',
    'role',
    'industry',
    'companyName',
    'startupStage',
    'coFounderNeeds',
    'pitchDeckLink',
    'youtubeVideoLink',
    'skills',
    'location',
    'whyImHere',
    'portfolioWebsiteLink',
    'industryExpertise',
    'companyWebsite',
    'languagesKnown',
  ],
  INCUBATORS: [
    'about',
    'headline',
    'role',
    'industry',
    'companyName',
    'incubationPrograms',
    'supportOffered',
    'skills',
    'location',
    'whyImHere',
    'portfolioWebsiteLink',
    'industryExpertise',
    'companyWebsite',
    'languagesKnown',
  ],
};

const DEFAULT_FIELDS = [
  'about',
  'headline',
  'role',
  'industry',
  'skills',
  'location',
  'whyImHere',
  'languagesKnown',
];

export function getVisibleCreatorFields(role) {
  if (!role) return DEFAULT_FIELDS;
  const key = String(role).toUpperCase();
  return CREATOR_FIELDS_BY_ROLE[key] || DEFAULT_FIELDS;
}

export function isCreatorFieldVisible(role, fieldName) {
  return getVisibleCreatorFields(role).includes(fieldName);
}
